import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState, useEffect } from 'react';
import PropagateLoader from "react-spinners/PropagateLoader";
import { isLabeledStatement } from 'typescript';

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  useEffect(() => {
    setIsLoading(true);;
    setTimeout(() => {
      setIsLoading(false);
    }, 15000);
  }, []);

  return (
    <>
      {
        isLoading ?
          <div className='h-screen flex items-center justify-center'>
            <PropagateLoader color='#FF9501' size='25' />
          </div>
          :
          <div>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="text-blue-500">
              <h1 className='text-3xl'>Nude pics</h1>
            </main>
          </div>
      }
    </>
  )
}
